<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RLE0517" name="validate Existing Custome" tests="4" failures="3" timestamp="30 Nov 2017 08:48:24 GMT" time="2.721" errors="0">
  <testcase name="login_to_application" time="0.646" classname="com.dw.api.automation.steps.ExistingOrgApiTest"/>
  <testcase name="validateExistingCustomer" time="0.608" classname="com.dw.api.automation.steps.ExistingOrgApiTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.steps.ExistingOrgApiTest.validateExistingCustomer(ExistingOrgApiTest.java:71)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateExistingCustomer -->
  <testcase name="validateExistingCustomerWithWrongOrganisationName" time="0.704" classname="com.dw.api.automation.steps.ExistingOrgApiTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.steps.ExistingOrgApiTest.validateExistingCustomerWithWrongOrganisationName(ExistingOrgApiTest.java:81)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateExistingCustomerWithWrongOrganisationName -->
  <testcase name="validateExistingCustomerWithWrongCompanyCode" time="0.599" classname="com.dw.api.automation.steps.ExistingOrgApiTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dw.api.automation.steps.ExistingOrgApiTest.validateExistingCustomerWithWrongCompanyCode(ExistingOrgApiTest.java:92)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateExistingCustomerWithWrongCompanyCode -->
</testsuite> <!-- validate Existing Custome -->
